default_platform(:ios)

platform :ios do
  desc "Build for TestFlight (stub)"
  lane :beta do
    puts "iOS build lane (stub)"
  end
end

platform :android do
  desc "Build for Internal track (stub)"
  lane :beta do
    puts "Android build lane (stub)"
  end
end
